config/routes.rb
Rails.application.routes.draw do
  resources :market_earnings

end

app/models/market_earning.rb
class MarketEarning < ActiveRecord::Base
  # file_to_pass = "ie_data.csv"

  validates :date, uniqueness: true
  validates :cape, presence: true

  def self.schiller_pe(file)
    sp500_data = CSV.read(file)
    all_pe = []
    sp500_data.each do |row|
      unless row.nil?
        unless row[0].nil? || row[10].nil?
          p "date: #{row[0]}, PE10: #{row[10]}"
          all_pe << row[10].to_f
        end
      end
    end
    p "total values: #{all_pe.length}"
    median(all_pe)
    mean_pe(all_pe)
    min_pe(all_pe)
    max_pe(all_pe)
    current_pe(all_pe)
  end

  def median(array)
    sorted = array.sort
    len = sorted.length
    p "median: #{(sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0}"
    (sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0
  end

  def mean_pe(array)
    len = array.length
    mean = array.inject(:+) / len
    p "mean: #{mean}"
    mean
  end

  def min_pe(array)
    p "min pe: #{array.min}"
  end

  def max_pe(array)
    p "max pe: #{array.max}"
  end

  def current_pe(array)
    p "current pe: #{array.last}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/market_earnings_controller.rb
class MarketEarningsController < ApplicationController
  before_action :set_market_earning, only: [:show, :edit, :update, :destroy]

  # GET /market_earnings
  # GET /market_earnings.json
  def index
    @market_earnings = MarketEarning.all
  end

  # GET /market_earnings/1
  # GET /market_earnings/1.json
  def show
  end

  # GET /market_earnings/new
  def new
    @market_earning = MarketEarning.new
  end

  # GET /market_earnings/1/edit
  def edit
  end

  # POST /market_earnings
  # POST /market_earnings.json
  def create
    @market_earning = MarketEarning.new(market_earning_params)

    respond_to do |format|
      if @market_earning.save
        format.html { redirect_to @market_earning, notice: 'Market earning was successfully created.' }
        format.json { render :show, status: :created, location: @market_earning }
      else
        format.html { render :new }
        format.json { render json: @market_earning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /market_earnings/1
  # PATCH/PUT /market_earnings/1.json
  def update
    respond_to do |format|
      if @market_earning.update(market_earning_params)
        format.html { redirect_to @market_earning, notice: 'Market earning was successfully updated.' }
        format.json { render :show, status: :ok, location: @market_earning }
      else
        format.html { render :edit }
        format.json { render json: @market_earning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /market_earnings/1
  # DELETE /market_earnings/1.json
  def destroy
    @market_earning.destroy
    respond_to do |format|
      format.html { redirect_to market_earnings_url, notice: 'Market earning was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market_earning
      @market_earning = MarketEarning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_earning_params
      params.require(:market_earning).permit(:date, :consumer_price_index, :dividend, :date_fraction, :long_interest_rate, :real_price, :real_dividend, :real_earnings, :cape)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market_earnings_helper.rb
module MarketEarningsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schiller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/market_earnings/_form.html.erb
<%= form_for(@market_earning) do |f| %>
  <% if @market_earning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market_earning.errors.count, "error") %> prohibited this market_earning from being saved:</h2>

      <ul>
      <% @market_earning.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :consumer_price_index %><br>
    <%= f.text_field :consumer_price_index %>
  </div>
  <div class="field">
    <%= f.label :dividend %><br>
    <%= f.text_field :dividend %>
  </div>
  <div class="field">
    <%= f.label :date_fraction %><br>
    <%= f.text_field :date_fraction %>
  </div>
  <div class="field">
    <%= f.label :long_interest_rate %><br>
    <%= f.text_field :long_interest_rate %>
  </div>
  <div class="field">
    <%= f.label :real_price %><br>
    <%= f.text_field :real_price %>
  </div>
  <div class="field">
    <%= f.label :real_dividend %><br>
    <%= f.text_field :real_dividend %>
  </div>
  <div class="field">
    <%= f.label :real_earnings %><br>
    <%= f.text_field :real_earnings %>
  </div>
  <div class="field">
    <%= f.label :cape %><br>
    <%= f.text_field :cape %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/market_earnings/edit.html.erb
<h1>Editing Market Earning</h1>

<%= render 'form' %>

<%= link_to 'Show', @market_earning %> |
<%= link_to 'Back', market_earnings_path %>

app/views/market_earnings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Market Earnings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Consumer price index</th>
      <th>Dividend</th>
      <th>Date fraction</th>
      <th>Long interest rate</th>
      <th>Real price</th>
      <th>Real dividend</th>
      <th>Real earnings</th>
      <th>Cape</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @market_earnings.each do |market_earning| %>
      <tr>
        <td><%= market_earning.date %></td>
        <td><%= market_earning.consumer_price_index %></td>
        <td><%= market_earning.dividend %></td>
        <td><%= market_earning.date_fraction %></td>
        <td><%= market_earning.long_interest_rate %></td>
        <td><%= market_earning.real_price %></td>
        <td><%= market_earning.real_dividend %></td>
        <td><%= market_earning.real_earnings %></td>
        <td><%= market_earning.cape %></td>
        <td><%= link_to 'Show', market_earning %></td>
        <td><%= link_to 'Edit', edit_market_earning_path(market_earning) %></td>
        <td><%= link_to 'Destroy', market_earning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market earning', new_market_earning_path %>

app/views/market_earnings/new.html.erb
<h1>New Market Earning</h1>

<%= render 'form' %>

<%= link_to 'Back', market_earnings_path %>

app/views/market_earnings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @market_earning.date %>
</p>

<p>
  <strong>Consumer price index:</strong>
  <%= @market_earning.consumer_price_index %>
</p>

<p>
  <strong>Dividend:</strong>
  <%= @market_earning.dividend %>
</p>

<p>
  <strong>Date fraction:</strong>
  <%= @market_earning.date_fraction %>
</p>

<p>
  <strong>Long interest rate:</strong>
  <%= @market_earning.long_interest_rate %>
</p>

<p>
  <strong>Real price:</strong>
  <%= @market_earning.real_price %>
</p>

<p>
  <strong>Real dividend:</strong>
  <%= @market_earning.real_dividend %>
</p>

<p>
  <strong>Real earnings:</strong>
  <%= @market_earning.real_earnings %>
</p>

<p>
  <strong>Cape:</strong>
  <%= @market_earning.cape %>
</p>

<%= link_to 'Edit', edit_market_earning_path(@market_earning) %> |
<%= link_to 'Back', market_earnings_path %>